name: vision_bot_mobile_app
description: "A new Flutter project for VisionBot - mobile robot with vision ai model."

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter_svg: ^2.2.3
  provider: ^6.1.5+1
  uuid: ^4.5.3
  model_viewer_plus: ^1.10.0
  flutter_joystick: ^0.2.2
  get_it: ^9.2.1
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  web_socket_channel: ^3.0.3
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.12.2
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.2.0
  riverpod_generator: ^4.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/svg/
    - assets/glb/
    - env/.ros.env
  fonts:
    - family: PS2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/UbuntuMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/UbuntuMono-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/UbuntuMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/UbuntuMono-BoldItalic.ttf
          weight: 700
          style: italic